from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ListingViewSet,BookingViewSet, InitiatePaymentView, VerifyPaymentView

# create an instance of the router
router = DefaultRouter()

# register the Viewset with a URl prefix
router.register(r'listings', ListingViewSet, basename ='listing')
router.register(r'bookings', BookingViewSet, basename = 'booking')

# url patterns now includes all the URLS generated by the router
urlpatterns = [
    path('api/v1/', include(router.urls)),

    # Initiates a new payment
    path('payments/initiate/<int:booking_id>/', InitiatePaymentView.as_view(), name='initiate_payment'),
    
    # Verification endpoint (used by Chapa's callback and the user's return redirect)
    path('payments/verify/<str:tx_ref>/', VerifyPaymentView.as_view(), name='verify_payment'),
    
]